/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _MSG_H_RPCGEN
#define _MSG_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct numbers {
	char *method;
};
typedef struct numbers numbers;

#define COMP_PROG 0x20000011
#define COMP_VERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define comp 1
extern  int * comp_1(numbers *, CLIENT *);
extern  int * comp_1_svc(numbers *, struct svc_req *);
extern int comp_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define comp 1
extern  int * comp_1();
extern  int * comp_1_svc();
extern int comp_prog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_numbers (XDR *, numbers*);

#else /* K&R C */
extern bool_t xdr_numbers ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_MSG_H_RPCGEN */
