/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "msg.h"

bool_t
xdr_numbers (XDR *xdrs, numbers *objp)
{
	register int32_t *buf;

	 if (!xdr_pointer (xdrs, (char **)&objp->method, sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	return TRUE;
}
