/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "msg.h"


void
comp_prog_1(char *host, char *a)
{
	CLIENT *clnt;
	int  *result_1;
	numbers  comp_1_arg;

#ifndef	DEBUG
	clnt = clnt_create (host, COMP_PROG, COMP_VERS, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */
	comp_1_arg.method = a;
	result_1 = comp_1(&comp_1_arg, clnt);
	if (result_1 == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	else {
		printf("the ascii of character is: %d\n", *result_1);
	}
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;

	if (argc < 3) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	comp_prog_1 (host, argv[2]);
exit (0);
}
